# Generated by Django 5.1.7 on 2025-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_osmtutorial_alter_diary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhigrosFanmadeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('difficulty', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('composer', models.CharField(max_length=80)),
                ('illustrator', models.CharField(max_length=80)),
                ('charter', models.CharField(max_length=80)),
                ('bpm', models.FloatField()),
                ('offset', models.FloatField()),
                ('notenum', models.IntegerField()),
            ],
        ),
    ]
