# Generated by Django 5.1.7 on 2025-03-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_phigrosfanmadechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='phigrosfanmadechart',
            name='illustration',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
