# Generated by Django 5.2 on 2025-04-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_phigrosfanmadechart_illustration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
