# Generated by Django 5.2 on 2025-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_diary_post_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phigrosfanmadechart',
            name='illustration',
        ),
        migrations.AddField(
            model_name='phigrosfanmadechart',
            name='bilibili_bv',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phigrosfanmadechart',
            name='phira_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phigrosfanmadechart',
            name='phizoen_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
