# Generated by Django 5.2 on 2025-07-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_phigrosfanmadechart_illustration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phigrosfanmadechart',
            old_name='phizoen_id',
            new_name='phizone_id',
        ),
    ]
