# Generated by Django 5.2 on 2026-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_phizoen_id_phigrosfanmadechart_phizone_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programming',
        ),
        migrations.AlterField(
            model_name='phigrosfanmadechart',
            name='phizone_id',
            field=models.CharField(max_length=36),
        ),
    ]
