# Generated by Django 5.2 on 2026-02-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_programming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phigrosfanmadechart',
            name='bilibili_bv',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='phigrosfanmadechart',
            name='phira_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phigrosfanmadechart',
            name='phizone_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
